# --
# Environment config file used by Figaro
# --
# Configure new developer environment by copying this file to
# config/application.yml and adding values.

DEVISE_SECRET_KEY: 
SENDGRID_USERNAME: 
SENDGRID_PASSWORD: 